export const ROLES = {
  BUYER: "BUYER",
  VENDOR: "VENDOR",
  ADMIN: "ADMIN",
};

export const ORDER_STATUS = {
  PROCESSING: "PROCESSING",
  CONFIRMED: "CONFIRMED",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
};

export const PAYMENT_STATUS = {
  PENDING: "PENDING",
  PAID: "PAID",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
};
